// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8DI8_x-6A2IZkd_1txhX622Z8FtvAjpQ',
    appId: '1:29143401213:web:9e72bb451c4bb29fb9b494',
    messagingSenderId: '29143401213',
    projectId: 'motionview-app',
    authDomain: 'motionview-app.firebaseapp.com',
    storageBucket: 'motionview-app.appspot.com',
    measurementId: 'G-BXW8W0Z6DD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh6BZTPh3T7mSgQBEUDaHsrDIKyhtJVuQ',
    appId: '1:29143401213:android:d5673195071eea6fb9b494',
    messagingSenderId: '29143401213',
    projectId: 'motionview-app',
    storageBucket: 'motionview-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCa0lqUILBaXH1PYyZigOAnDP7V3DBVXM',
    appId: '1:29143401213:ios:897256715b4d40c7b9b494',
    messagingSenderId: '29143401213',
    projectId: 'motionview-app',
    storageBucket: 'motionview-app.appspot.com',
    androidClientId: '29143401213-08b8bdn27c3cfabaqte9ub0p0eiemcdg.apps.googleusercontent.com',
    iosClientId: '29143401213-9og1ro2989figg14db123blamah6suvb.apps.googleusercontent.com',
    iosBundleId: 'bd.com.motionview.motionview',
  );
}
